[Interface]
PrivateKey = cJvJKpjJtszNEjINp4qStX/jl4MqS7S8TBNBklCCyks=
Address = 10.10.5.85/32
DNS = 192.168.88.1

[Peer]
PublicKey = pnTSjr+u2boRocM3GSSjTPQNjx6pAvtiJSTWlyyEFCM=
AllowedIPs = 192.168.88.0/24
Endpoint = 91.187.224.3:13231
PersistentKeepalive = 25
